locale: en-gb

method: sqlite
host:
database:

updates:
  check: false
  repository: https://api.github.com/repos/lush-love/aesthetic

embed:
  color:
    default: 0xFFFFFF
    warn: 0xE67E22
    error: 0xE74C3C
  footer:
    text: Aesthetic
    icon: https://i.imgur.com/PQY5oE6.png